### ISSUE TITLE
Code Snippet Issues

### ISSUE THREAD

**Issue by Thundax** [laCour/slack-night-mode#136]
The code snippet window outline and border is solid white.
The background is black and the standard text is dark grey, hard to see.
Contextually colored text appears fine.

**Comment by FelixVicis** [comment]
Not just Windows.
![image](https://user-images.githubusercontent.com/6580094/35246432-86ed53a6-ff7b-11e7-92c5-d1ff5fd263c0.png)

OS: Ubuntu 16.04
Browser: Chrome 63.0

**Comment by stefano-m** [comment]
@laCour Adding `color` to `.CodeMirror pre` fixes the style for me.

```css
.CodeMirror pre {
    background: transparent !important;
    color: #e6e6e6;
}
```
