### ISSUE TITLE
Thread text field is white

### ISSUE THREAD

**Issue by keith** [laCour/slack-night-mode#180]
The text field in the thread view no longer matches the rest of the theme:

![image](https://user-images.githubusercontent.com/283886/43598380-64a8e134-9639-11e8-87d0-7fbe4477cdb0.png)

I believe this started happening after Slack updated to allow images in threads.

**Comment by roko-p** [comment]
Adding `background-color: #545454` to the CSS rule which is currently: 
```css
#message_edit_container .message_input, .inline_message_input_container .message_input { color: #e6e6e6;  }
```
fixed it for me.

So I edited this for myself, and am using the updated built css from [this gist](https://gist.github.com/roko-p/b0d27963bbe2ad9abc1444df6433f453). (Feel free to link to that if this quick fix is good enough for you)

--------

Didn't make a pull request because I'm not sure where exactly and how this should be done in the .scss files.
Also the white background of the button should probably be styled as well, but it's not a problem to me so I didn't bother

**Comment by nmielnik** [comment]
Adding this selector fixed both the textbox and the button color:

```css
#reply_container div.inline_message_input_container.with_file_upload {
  background: padding-box #545454;
  border-color: #424242;
  color: #e6e6e6;
}
```

there definitely could be another way to go about this, but targeting the `.inline_message_input_contaner` element itself controls the background of both the textbox and the button with the `+`
