### ISSUE TITLE
Small white line on edge of #client-body:before can be removed

### ISSUE THREAD

**Issue by spikespaz** [laCour/slack-night-mode#187]
![Issue Screenshot Cropped](https://user-images.githubusercontent.com/12502988/45934848-dbc5ca00-bf58-11e8-91e8-c2431efb1e59.png)

```css
#client_body:not(.onboarding):not(.feature_global_nav_layout):before {
  display: none;
}
```

This CSS works and doesn't break anything but I don't know where to put it, otherwise I would submit a PR.
