### ISSUE TITLE
Tiny white bar next to top left user name area

### ISSUE THREAD

**Issue by tzm41** [laCour/slack-night-mode#202]
![image](https://user-images.githubusercontent.com/5728283/50609199-fc2ceb00-0e9c-11e9-9907-0b02ac0f0dd8.png)

There is a very tiny white vertical bar next to the top left user name area, when the theme is used in the Slack mac client. This has been there for a couple months, but I don't know if using the theme in the client app is supported or not...

**Comment by Lemmmy** [comment]
Exists in Chrome Slack on Linux too. The element is `#client_body:before`, specifically the selector `#client_body:not(.onboarding):not(.feature_global_nav_layout):before`. Adds the following three rules which affect it:

```css
#client_body:not(.onboarding):not(.feature_global_nav_layout):before {
	border-bottom: 1px solid rgba(0,0,0,.1);
	background: #fff;
	box-shadow: inset 1px 0 0 0 #e8e8e8;
}
```
