### ISSUE TITLE
The "All Threads" view is not styled and garishly white.

### ISSUE THREAD

**Issue by Drarok** [laCour/slack-night-mode#218]
I've collected some custom styles in order to combat this, which makes it look less bad overall, but still needs improving.

```css
.p-threads_view {
  background: #222;
}

.p-threads_view__divider_line {
  border-color: #111;
}

.p-threads_view__divider_label {
  background: #111;
}

.p-threads_view_header__channel_name {
  color: #c7c7c7;
}

.p-threads_view_root {
  border-color: #444;
}

.p-threads_view_reply {
  border-color: #444;
}

.p_threads_view_load_newer_button,
.p_threads_view_load_older_button {
  background: rgba(255, 255, 255, 0.05);
  border-color: #444;
}

.p-threads_view__footer {
  border-color: #444;
}

.p-threads_view__default_background {
  background: rgba(255, 255, 255, 0.05);
}
```

Before:
<img width="1141" alt="Screenshot 2019-03-15 at 17 28 59" src="https://user-images.githubusercontent.com/55830/54450410-3aba0e00-4748-11e9-8b3a-29313760b6e4.png">

After:
<img width="1149" alt="Screenshot 2019-03-15 at 17 30 46" src="https://user-images.githubusercontent.com/55830/54450422-41488580-4748-11e9-97f7-51fdefc30a41.png">

**Comment by Lemmmy** [comment]
Seems that `#threads-msgs` has changed to `.p-threads_view`, the whole UI has been re-done:

https://github.com/laCour/slack-night-mode/blob/master/scss/modules/messaging/_threads.scss

**Comment by mxr** [comment]
@Drarok thanks for the workaround. I'm using it in the meantime. I also added this locally:

```css
.p-threads_view_reply--new_reply {
      background: rgba(255, 255, 255, 0.05);
}
```

Otherwise new replies in the all-threads view have too light of a background.
