### ISSUE TITLE
header and input styles are broken by new July 2019 slack update

### ISSUE THREAD

**Issue by micahstubbs** [laCour/slack-night-mode#235]
here is a gist with my quick fixes 

https://gist.github.com/micahstubbs/e750e5bb8b6adb7b51a961e57660f710

**Comment by micahstubbs** [comment]
fixes inline

```css
/* ==UserStyle==
2
@name           slack-dark-mode-201907-fixes
3
@namespace      github.com/openstyles/stylus
4
@version        1.0.0
5
@description    slack-dark-mode-201907-fixes
6
@author         @micahstubbs
7
==/UserStyle== */

/* for use with  */
/* Slack Night Mode (Black) by lacour */
/* https://userstyles.org/styles/117475/slack-night-mode-black */
@-moz-document regexp("https://[^./]*\\.slack\\.com/(?!pricing)(?!security).*") {
  .p-classic_nav__model_header {
    /*body dark gray*/
    background: #000;
    opacity: 0.86;
  }

  .p-classic_nav__right_header {
    /*body dark gray*/
    background: #000;
    opacity: 0.86;
  }

  .p-workspace__primary_view_footer {
    /*body dark gray*/
    background: #000;
    opacity: 0.86;
  }

  .p-classic_nav__team_header {
    /*sidebar medium gray*/
    background: #363636;
  }

  .p-workspace__input .p-message_input_field {
    /*sidebar light gray*/
    background: #363636;
    border-color: #545454;
  }

  .c-virtual_list .c-virtual_list--scrollbar .c-scrollbar .c-scrollbar--hidden {
    /*sidebar light gray*/
    background: #363636;
    border-color: #545454;
  }

  .c-scrollbar__hider {
    /*sidebar light gray*/
    background: #363636;
    border-color: #545454;
  }

  .p-workspace__secondary_view {
    border-color: #545454;
  }

  .p-workspace__primary_view_footer {
    border-color: #545454;
  }
}
```
