### ISSUE TITLE
Flexpane has white border

### ISSUE THREAD

**Issue by laCour** [laCour/slack-night-mode#80]
![image](https://cloud.githubusercontent.com/assets/126202/18215290/c0b2ed24-710d-11e6-9039-e5cd2d9bd742.png)

**Comment by shrimpza** [comment]
I'm not too familiar with your codebase so I'm not sure how to factor a permanent fix in, but I fixed this temporarily on my end with a custom style:

``` css
#col_flex {
  background: none;
}
```
