### ISSUE TITLE
White section behind notification bars

### ISSUE THREAD

**Issue by laCour** [laCour/slack-night-mode#85]
Offending CSS:

``` css
#messages_container.has_reply_banners.has_top_messages_banner #reply_banners:after,#messages_container:not(.has_reply_banners).has_top_messages_banner:before{content:'';position:absolute;z-index:98;top:.46875rem;left:0;right:.8125rem;height:1.625rem;background:#fff}
```
